#!/bin/sh

[ -e Makefile ] && make clean
rm -rf autom4te.cache configure Makefile stamp-h1 
rm -rf src/Makefile src/.deps
rm -rf Makefile.in aclocal.m4 config.log config.h
rm -rf depcomp missing install-sh config.status

# Run the autoconf steps
aclocal && \
autoheader && \
automake --gnu --add-missing -c && \
autoconf &&
glibtoolize
